//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Producto.Application.Messages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesProducto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesProducto() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Producto.Application.Messages.MessagesProducto", typeof(MessagesProducto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un conflicto al momento de crear el producto.
        /// </summary>
        public static string CreateProductoConflict {
            get {
                return ResourceManager.GetString("CreateProductoConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al crear el nuevo producto.
        /// </summary>
        public static string CreateProductoError {
            get {
                return ResourceManager.GetString("CreateProductoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se creo el nuevo producto correctamente.
        /// </summary>
        public static string CreateProductoOk {
            get {
                return ResourceManager.GetString("CreateProductoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un conflicto al eliminar el producto seleccionado.
        /// </summary>
        public static string DeleteProductoConflict {
            get {
                return ResourceManager.GetString("DeleteProductoConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al eliminar el producto seleccionado.
        /// </summary>
        public static string DeleteProductoError {
            get {
                return ResourceManager.GetString("DeleteProductoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino correctamente el producto seleccionado.
        /// </summary>
        public static string DeleteProductoOk {
            get {
                return ResourceManager.GetString("DeleteProductoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron productos.
        /// </summary>
        public static string GetAllProductoNotFound {
            get {
                return ResourceManager.GetString("GetAllProductoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro el producto con el ID ingresado.
        /// </summary>
        public static string GetByIdProductoNotFound {
            get {
                return ResourceManager.GetString("GetByIdProductoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro el producto con el nombre ingresado.
        /// </summary>
        public static string GetByNameProductoNotFound {
            get {
                return ResourceManager.GetString("GetByNameProductoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un conflicto al actualizar los datos del producto.
        /// </summary>
        public static string UpdateProductoConflict {
            get {
                return ResourceManager.GetString("UpdateProductoConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al actualizar los datos del producto seleccionado.
        /// </summary>
        public static string UpdateProductoError {
            get {
                return ResourceManager.GetString("UpdateProductoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizaron correctamente los datos del producto.
        /// </summary>
        public static string UpdateProductoOK {
            get {
                return ResourceManager.GetString("UpdateProductoOK", resourceCulture);
            }
        }
    }
}
